import 'package:flutter/material.dart';
import 'package:quran_one/core/theme/color/q_ref_colors.dart';
import 'package:quran_one/core/theme/q_theme_mode.dart';

/// Hand-authored schemes, never ColorScheme.fromSeed.
///
/// Seed generation cannot guarantee the contrast floors this product commits
/// to: 12:1 on Quranic text, 8:1 on translation, 5.5:1 on body.
abstract final class QSchemes {
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: QRef.primary,
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: QRef.primaryContainerLight,
    onPrimaryContainer: QRef.onPrimaryContainerLight,
    secondary: QRef.secondary,
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: QRef.secondaryContainerLight,
    onSecondaryContainer: QRef.onSecondaryContainerLight,
    tertiary: QRef.tertiary,
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: QRef.tertiaryContainerLight,
    onTertiaryContainer: QRef.onTertiaryContainerLight,
    error: QRef.error,
    onError: Color(0xFFFFFFFF),
    errorContainer: QRef.errorContainerLight,
    onErrorContainer: QRef.onErrorContainerLight,
    surface: QRef.bgLight,
    onSurface: QRef.textLight,
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFFBF8F3),
    surfaceContainer: Color(0xFFF6F1E9),
    surfaceContainerHigh: Color(0xFFF1EBE1),
    surfaceContainerHighest: Color(0xFFEBE4D8),
    onSurfaceVariant: QRef.textMutedLight,
    outline: QRef.borderStrongLight,
    outlineVariant: QRef.dividerLight,
    inverseSurface: QRef.inverseSurfaceLight,
    onInverseSurface: QRef.onInverseSurfaceLight,
    inversePrimary: QRef.primaryDark,
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: QRef.primaryDark,
    onPrimary: QRef.onPrimaryDark,
    primaryContainer: QRef.primaryContainerDark,
    onPrimaryContainer: QRef.onPrimaryContainerDark,
    secondary: QRef.secondaryDark,
    onSecondary: QRef.onSecondaryDark,
    secondaryContainer: QRef.secondaryContainerDark,
    onSecondaryContainer: QRef.onSecondaryContainerDark,
    tertiary: QRef.tertiaryDark,
    onTertiary: QRef.onTertiaryDark,
    tertiaryContainer: QRef.tertiaryContainerDark,
    onTertiaryContainer: QRef.onTertiaryContainerDark,
    error: QRef.errorDark,
    onError: QRef.onErrorDark,
    errorContainer: QRef.errorContainerDark,
    onErrorContainer: Color(0xFFF9DEDC),
    surface: QRef.bgDark,
    onSurface: QRef.textDark,
    surfaceContainerLowest: Color(0xFF0E1013),
    surfaceContainerLow: Color(0xFF16191D),
    surfaceContainer: Color(0xFF1A1D22),
    surfaceContainerHigh: Color(0xFF212429),
    surfaceContainerHighest: Color(0xFF282C32),
    onSurfaceVariant: QRef.textMutedDark,
    outline: QRef.borderStrongDark,
    outlineVariant: QRef.dividerDark,
    inverseSurface: Color(0xFFE4E1DC),
    onInverseSurface: Color(0xFF14161A),
    inversePrimary: QRef.primary,
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
  );

  static const amoled = ColorScheme(
    brightness: Brightness.dark,
    primary: QRef.primaryDark,
    onPrimary: QRef.onPrimaryDark,
    primaryContainer: QRef.primaryContainerAmoled,
    onPrimaryContainer: QRef.onPrimaryContainerDark,
    secondary: QRef.secondaryDark,
    onSecondary: QRef.onSecondaryDark,
    secondaryContainer: QRef.secondaryContainerAmoled,
    onSecondaryContainer: QRef.onSecondaryContainerDark,
    tertiary: QRef.tertiaryDark,
    onTertiary: QRef.onTertiaryDark,
    tertiaryContainer: QRef.tertiaryContainerAmoled,
    onTertiaryContainer: QRef.onTertiaryContainerDark,
    error: QRef.errorDark,
    onError: QRef.onErrorDark,
    errorContainer: QRef.errorContainerAmoled,
    onErrorContainer: Color(0xFFF9DEDC),
    surface: QRef.bgAmoled,
    onSurface: QRef.textAmoled,
    surfaceContainerLowest: Color(0xFF000000),
    surfaceContainerLow: Color(0xFF0A0A0B),
    surfaceContainer: Color(0xFF0E0F11),
    surfaceContainerHigh: Color(0xFF141416),
    surfaceContainerHighest: Color(0xFF1A1A1C),
    onSurfaceVariant: QRef.textMutedAmoled,
    outline: QRef.borderStrongAmoled,
    outlineVariant: QRef.dividerAmoled,
    inverseSurface: Color(0xFFD9D6D1),
    onInverseSurface: Color(0xFF000000),
    inversePrimary: QRef.primary,
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
  );

  static ColorScheme forMode(QThemeMode mode) => switch (mode) {
        QThemeMode.light => light,
        QThemeMode.dark => dark,
        QThemeMode.amoled => amoled,
      };
}
